# Simple Neural Network from Scratch, [Perceptron](https://es.wikipedia.org/wiki/Perceptrón)

In [1]:
import numpy as np

In [12]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
  return x * (1 - x)

training_inputs = np.array([[0,0,1], 
                            [1,1,1],
                            [1,0,1],
                            [0,0,1]])

training_outputs = np.array([[0,1,1,0]]).T
np.random.seed(1)
synaptic_weights = 2 * np. random. random ((3, 1)) - 1

print('Random starting synaptic weights: ')
print(synaptic_weights)

for iteration in range(10000):
  input_layer = training_inputs
  outputs = sigmoid(np.dot(input_layer, synaptic_weights))
  error = training_outputs - outputs
  adjustements = error * sigmoid_derivative(outputs)
  synaptic_weights += np.dot(input_layer.T, adjustements)

print('Synaptics weights after training: ')
print(synaptic_weights)

print('Outputs after training: ')
print(outputs) 

Random starting synaptic weights: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]
Synaptics weights after training: 
[[ 9.31872048]
 [ 1.64174925]
 [-4.72268986]]
Outputs after training: 
[[0.00881332]
 [0.99804951]
 [0.99000851]
 [0.00881332]]
